// <copyright file="GraphQLTestQueryResult.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text;

namespace ProfileLocation.WebAPI.Tests.Utils
{
    public class GraphQLTestQueryResult
    {
        public string Query { get; set; }
        public string ExpectedResult { get; set; }
        public GraphQLQueryType Type { get; set; }
    }

    public enum GraphQLQueryType
    {
        UpSert,
        Get,
        Search
    }
}
