// <copyright file="IEntityObjectEventService.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text;
using ProfileLocation.Domain.ORM.Models.Communications;

namespace ProfileLocation.Domain.ORM.Interfaces
{
    public interface IEntityObjectEventService
    {
        void RaiseObjectEvent(EntityObjectEventMessageModel message);

        event EventHandler<EntityObjectEventMessageModel> EntityObjectEvent;
    }
}
