// <copyright file="ILogManager.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;

namespace ProfileLocation.Domain.ORM.Interfaces
{
    public interface ILogManager
    {
        void Fatal(string message, Exception ex);
        void Error(string message, Exception ex = null);
        void Warning(string message, Exception ex = null);
        void Info(string message, Exception ex = null);
        void Debug(string message, Exception ex = null);
    }
}
