// <copyright file="IModelContext.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace ProfileLocation.Domain.ORM.Interfaces
{
    public interface IModelContext
    {
        bool Commit();
        Task<bool> CommitAsync();
    }
}
