// <copyright file="IValidatorStrategy.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System.Collections;
using System.Collections.Generic;

namespace ProfileLocation.Domain.ORM.Interfaces
{
    public interface IValidatorStrategy<T>
    {
        bool IsValid(T validateThis);
        IList<string> Validate(T validateThis, bool recursive = false);
    }
}
