// <copyright file="SortOrderModel.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text;
using ProfileLocation.Domain.ORM.Enums;

namespace ProfileLocation.Domain.ORM.Models.Input
{
    public class SortOrderModel
    {
        public string Field { get; set; }
        public SortDirectionEnum Direction { get; set; }
    }
}
