// <copyright file="ErrorModel.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProfileLocation.WebAPI.Models.GraphQL
{
    public class ErrorModel
    {
        public string ErrorCode { get; set; }
        public string Message { get; set; }
        public string ExceptionType { get; set; }
        public string Debug { get; set; }
    }
}
