// <copyright file="IntSearchType.cs" company="Victor Saly Ltd">
// Copyright (c) Victor Saly Ltd. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Shared
{
    public class BooleanSearchType : BaseSearchType
    {
        public BooleanSearchType()
        {
            Name = "BooleanSearch";
            Description = "Boolean search";

            Field<BooleanGraphType>("value");
        }
    }
}
