// <copyright file="FloatSearchType.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Shared
{
    public class FloatSearchType : BaseSearchType
    {
        public FloatSearchType()
        {
            Name = "FloatSearch";
            Description = "Integer search, used for float, double.";
            var fldMethod = Field<NumberSearchMethodEnumType>("method");
            fldMethod.Description = "Operator";
            fldMethod.DefaultValue = NumberSearchMethodEnumType.Equal;

            Field<ListGraphType<FloatGraphType>>("values");
        }
    }
}
