// <copyright file="IntSearchType.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Shared
{
    public class IntSearchType : BaseSearchType
    {
        public IntSearchType()
        {
            Name = "IntSearch";
            Description = "Integer search, used for byte, short, int, long.";
            var fldMethod = Field<NumberSearchMethodEnumType>("method");
            fldMethod.Description = "Operator";
            fldMethod.DefaultValue = NumberSearchMethodEnumType.Equal;

            Field<ListGraphType<LongGraphType>>("values");
        }
    }
}
