// <copyright file="ScalarSearchType.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Shared
{
    public class ScalarSearchType<TScalarGraphType> : BaseSearchType where TScalarGraphType : GraphType
    {
        public ScalarSearchType()
        {
            Name = $"{typeof(TScalarGraphType).Name}ScalarSearch";
            Field<TScalarGraphType>("value", "Value");
        }
    }
}
