// <copyright file="StringSearchMethodEnumType.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Shared
{
    public class StringSearchMethodEnumType : EnumerationGraphType
    {
        public StringSearchMethodEnumType()
        {
            Name = "StringSearchMethod";
            AddValue(Equals, "=", Equals);
            AddValue(NotEqual, "<>", NotEqual);
            AddValue(StartsWith, "(term)%", StartsWith);
            AddValue(Contains, "%(term)%", Contains);
            AddValue(EndsWith, "%(term)", EndsWith);
        }

        public new const string Equals = "equals";
        public const string NotEqual = "notEqual";
        public const string StartsWith = "startsWith";
        public const string Contains = "contains";
        public const string EndsWith = "endsWith";
    }
}
