// <copyright file="StringSearchType.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraphQL.Language.AST;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Shared
{
    public class StringSearchType : BaseSearchType
    {
        public StringSearchType()
        { 
            Field<ListGraphType<StringGraphType>>("values");

            var strFld = Field<StringSearchMethodEnumType>("method");
            strFld.DefaultValue = StringSearchMethodEnumType.Equals;
        }
    }
}
