// <copyright file="ProfileLocationContext.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using ProfileLocation.Data.EF.Entities;

namespace ProfileLocation.Data.EF.Contexts
{
    /// <summary>
    /// Class to override EF generated context
    /// </summary>
    public class ProfileLocationContext : ProfileLocationContextEF
    {
        public ProfileLocationContext()
        {

        }

        public ProfileLocationContext(DbContextOptions<ProfileLocationContextEF> options) : base(options)
        {
            
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            //Override any EF properties here

            #region Entity Overrides

            // modelBuilder.Entity<Stock>().Ignore(i => i.IngramPartNo);
            // modelBuilder.Entity<Stock>().Ignore(i => i.C2000partNo);
            //modelBuilder.Entity<User>().Property(p => p.MsreplTranVersion).HasDefaultValueSql("(newsequentialid())");

            #endregion
        }
    }
}
