// <copyright file="GroupInputType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Input
{
    public class GroupInputType : InputObjectGraphType
    {
        public GroupInputType()
        {
            Name = "GroupInput";
            Description = "GroupInputModel";
			
            Field(typeof(int).GetGraphTypeFromType(true), "Id");
            Field(typeof(string).GetGraphTypeFromType(true), "Name");
            Field(typeof(string).GetGraphTypeFromType(true), "Description");
            Field(typeof(DateTime).GetGraphTypeFromType(true), "Created");
            Field(typeof(bool).GetGraphTypeFromType(true), "IsDeleted");
		}
	}
}