// <copyright file="LocationInputType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Input
{
    public class LocationInputType : InputObjectGraphType
    {
        public LocationInputType()
        {
            Name = "LocationInput";
            Description = "LocationInputModel";
			
            Field(typeof(int).GetGraphTypeFromType(true), "Id");
            Field(typeof(string).GetGraphTypeFromType(true), "Address");
            Field(typeof(string).GetGraphTypeFromType(true), "ViewPort");
            Field(typeof(string).GetGraphTypeFromType(true), "Location1");
            Field(typeof(int).GetGraphTypeFromType(true), "PlaceId");
            Field(typeof(int).GetGraphTypeFromType(), "ProfileId");
		}
	}
}