// <copyright file="ProfileInputType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Input
{
    public class ProfileInputType : InputObjectGraphType
    {
        public ProfileInputType()
        {
            Name = "ProfileInput";
            Description = "ProfileInputModel";
			
            Field(typeof(int).GetGraphTypeFromType(true), "Id");
            Field(typeof(string).GetGraphTypeFromType(true), "Username");
            Field(typeof(string).GetGraphTypeFromType(true), "Name");
            Field(typeof(string).GetGraphTypeFromType(true), "Bio");
            Field(typeof(string).GetGraphTypeFromType(true), "Nicknames");
            Field(typeof(string).GetGraphTypeFromType(true), "Email");
            Field(typeof(string).GetGraphTypeFromType(true), "Country");
            Field(typeof(string).GetGraphTypeFromType(true), "Mobile");
            Field(typeof(int).GetGraphTypeFromType(true), "LocationId");
            Field(typeof(string).GetGraphTypeFromType(true), "PhotoUrl");
            Field(typeof(bool).GetGraphTypeFromType(true), "IsApproved");
            Field(typeof(bool).GetGraphTypeFromType(true), "IsAdmin");
            Field(typeof(bool).GetGraphTypeFromType(true), "IsActive");
            Field(typeof(Guid).GetGraphTypeFromType(true), "Guid");
		}
	}
}