// <copyright file="ProfileGroupInputType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Input
{
    public class ProfileGroupInputType : InputObjectGraphType
    {
        public ProfileGroupInputType()
        {
            Name = "ProfileGroupInput";
            Description = "ProfileGroupInputModel";
			
            Field(typeof(int).GetGraphTypeFromType(true), "Id");
            Field(typeof(int).GetGraphTypeFromType(true), "ProfileId");
            Field(typeof(int).GetGraphTypeFromType(true), "GroupId");
            Field(typeof(bool).GetGraphTypeFromType(true), "IsActive");
            Field(typeof(bool).GetGraphTypeFromType(true), "IsDeleted");
		}
	}
}