// <copyright file="SocialTypeInputType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Input
{
    public class SocialTypeInputType : InputObjectGraphType
    {
        public SocialTypeInputType()
        {
            Name = "SocialTypeInput";
            Description = "SocialTypeInputModel";
			
            Field(typeof(int).GetGraphTypeFromType(true), "Id");
            Field(typeof(string).GetGraphTypeFromType(true), "Name");
            Field(typeof(string).GetGraphTypeFromType(true), "IconUrl");
            Field(typeof(bool).GetGraphTypeFromType(true), "IsDeleted");
		}
	}
}