// <copyright file="SocialInputType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;

namespace ProfileLocation.WebAPI.Models.GraphQL.Input
{
    public class SocialInputType : InputObjectGraphType
    {
        public SocialInputType()
        {
            Name = "SocialInput";
            Description = "SocialInputModel";
			
            Field(typeof(int).GetGraphTypeFromType(true), "Id");
            Field(typeof(int).GetGraphTypeFromType(true), "SocialTypeId");
            Field(typeof(string).GetGraphTypeFromType(true), "Value");
            Field(typeof(string).GetGraphTypeFromType(true), "PhotoUrl");
            Field(typeof(bool).GetGraphTypeFromType(true), "IsDeleted");
            Field(typeof(int).GetGraphTypeFromType(true), "ProfileId");
		}
	}
}