// <copyright file="LocationSearchType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;
using ProfileLocation.WebAPI.Models.GraphQL.Shared;
using ProfileLocation.Data.EF.Entities;
using ProfileLocation.Domain.ORM.Models;

namespace ProfileLocation.WebAPI.Models.GraphQL.Search
{
	public class LocationSearchType : InputObjectGraphType
	{
		public LocationSearchType()
		{
            Name = "LocationSearch";
			Description = "Location SearchContext";


            Field(typeof(ListGraphType<IntSearchType>), "Id");
        

            Field(typeof(ListGraphType<StringSearchType>), "Address");
        

            Field(typeof(ListGraphType<StringSearchType>), "ViewPort");
        

            Field(typeof(ListGraphType<StringSearchType>), "Location1");
        

            Field(typeof(ListGraphType<IntSearchType>), "PlaceId");
        

            Field(typeof(ListGraphType<IntSearchType>), "ProfileId");
        

            var fldProfiles = Field(typeof(ProfileSearchType), "Profiles");
			fldProfiles.Description = "Searches for matches in Profiles";
        
    
        }

    }

}