// <copyright file="ProfileSearchType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;
using ProfileLocation.WebAPI.Models.GraphQL.Shared;
using ProfileLocation.Data.EF.Entities;
using ProfileLocation.Domain.ORM.Models;

namespace ProfileLocation.WebAPI.Models.GraphQL.Search
{
	public class ProfileSearchType : InputObjectGraphType
	{
		public ProfileSearchType()
		{
            Name = "ProfileSearch";
			Description = "Profile SearchContext";


            Field(typeof(ListGraphType<IntSearchType>), "Id");
        

            Field(typeof(ListGraphType<StringSearchType>), "Username");
        

            Field(typeof(ListGraphType<StringSearchType>), "Name");
        

            Field(typeof(ListGraphType<StringSearchType>), "Bio");
        

            Field(typeof(ListGraphType<StringSearchType>), "Nicknames");
        

            Field(typeof(ListGraphType<StringSearchType>), "Email");
        

            Field(typeof(ListGraphType<StringSearchType>), "Country");
        

            Field(typeof(ListGraphType<StringSearchType>), "Mobile");
        

            Field(typeof(ListGraphType<IntSearchType>), "LocationId");
        

            Field(typeof(ListGraphType<StringSearchType>), "PhotoUrl");
        

            Field(typeof(ListGraphType<BooleanSearchType>), "IsApproved");
        

            Field(typeof(ListGraphType<BooleanSearchType>), "IsAdmin");
        

            Field(typeof(ListGraphType<BooleanSearchType>), "IsActive");
        

            Field(typeof(ListGraphType<ScalarSearchType<GuidGraphType>>), "Guid");
        

            Field(typeof(LocationSearchType), "Location");
        
    
            var fldProfileGroups = Field(typeof(ProfileGroupSearchType), "ProfileGroups");
			fldProfileGroups.Description = "Searches for matches in ProfileGroups";
        
    
            var fldSocials = Field(typeof(SocialSearchType), "Socials");
			fldSocials.Description = "Searches for matches in Socials";
        
    
        }

    }

}