// <copyright file="ProfileGroupSearchType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;
using ProfileLocation.WebAPI.Models.GraphQL.Shared;
using ProfileLocation.Data.EF.Entities;
using ProfileLocation.Domain.ORM.Models;

namespace ProfileLocation.WebAPI.Models.GraphQL.Search
{
	public class ProfileGroupSearchType : InputObjectGraphType
	{
		public ProfileGroupSearchType()
		{
            Name = "ProfileGroupSearch";
			Description = "ProfileGroup SearchContext";


            Field(typeof(ListGraphType<IntSearchType>), "Id");
        

            Field(typeof(ListGraphType<IntSearchType>), "ProfileId");
        

            Field(typeof(ListGraphType<IntSearchType>), "GroupId");
        

            Field(typeof(ListGraphType<BooleanSearchType>), "IsActive");
        

            Field(typeof(ListGraphType<BooleanSearchType>), "IsDeleted");
        

            Field(typeof(GroupSearchType), "Group");
        
    
            Field(typeof(ProfileSearchType), "Profile");
        
    
        }

    }

}