// <copyright file="SocialSearchType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;
using ProfileLocation.WebAPI.Models.GraphQL.Shared;
using ProfileLocation.Data.EF.Entities;
using ProfileLocation.Domain.ORM.Models;

namespace ProfileLocation.WebAPI.Models.GraphQL.Search
{
	public class SocialSearchType : InputObjectGraphType
	{
		public SocialSearchType()
		{
            Name = "SocialSearch";
			Description = "Social SearchContext";


            Field(typeof(ListGraphType<IntSearchType>), "Id");
        

            Field(typeof(ListGraphType<IntSearchType>), "SocialTypeId");
        

            Field(typeof(ListGraphType<StringSearchType>), "Value");
        

            Field(typeof(ListGraphType<StringSearchType>), "PhotoUrl");
        

            Field(typeof(ListGraphType<BooleanSearchType>), "IsDeleted");
        

            Field(typeof(ListGraphType<IntSearchType>), "ProfileId");
        

            Field(typeof(ProfileSearchType), "Profile");
        
    
            Field(typeof(SocialTypeSearchType), "SocialType");
        
    
        }

    }

}