// <copyright file="SocialTypeSearchType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using GraphQL;
using GraphQL.Types;
using ProfileLocation.WebAPI.Models.GraphQL.Shared;
using ProfileLocation.Data.EF.Entities;
using ProfileLocation.Domain.ORM.Models;

namespace ProfileLocation.WebAPI.Models.GraphQL.Search
{
	public class SocialTypeSearchType : InputObjectGraphType
	{
		public SocialTypeSearchType()
		{
            Name = "SocialTypeSearch";
			Description = "SocialType SearchContext";


            Field(typeof(ListGraphType<IntSearchType>), "Id");
        

            Field(typeof(ListGraphType<StringSearchType>), "Name");
        

            Field(typeof(ListGraphType<StringSearchType>), "IconUrl");
        

            Field(typeof(ListGraphType<BooleanSearchType>), "IsDeleted");
        

            var fldSocials = Field(typeof(SocialSearchType), "Socials");
			fldSocials.Description = "Searches for matches in Socials";
        
    
        }

    }

}