// <copyright file="SortOrderEnumType.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraphQL.Types;
using ProfileLocation.Domain.ORM.Enums;

namespace ProfileLocation.WebAPI.Models.GraphQL.Shared
{
    public class SortOrderEnumType : EnumerationGraphType<SortDirectionEnum>
    {
        public SortOrderEnumType()
        {
        }
    }
}
