// <copyright file="SortOrderType.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraphQL.Types;
using ProfileLocation.Domain.ORM.Enums;
using ProfileLocation.Domain.ORM.Models.Input;

namespace ProfileLocation.WebAPI.Models.GraphQL.Shared
{
    public class SortOrderType<TEntityEnumType> : InputObjectGraphType<SortOrderModel> where TEntityEnumType : GraphType
    {
        public SortOrderType()
        {
            Name = typeof(TEntityEnumType).Name + "SortOrder";
            Field<NonNullGraphType<TEntityEnumType>>("Field");
            var sortFld = Field<SortOrderEnumType>("Direction", "");
            sortFld.DefaultValue = SortDirectionEnum.ASC;
        }
    }
}
