// <copyright file="EntityObjectEventTypeEnum.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text;

namespace ProfileLocation.Domain.ORM.Enums
{
    public enum EntityObjectEventTypeEnum
    {
        Added,
        Modified
    }
}
