// <copyright file="IUserContext.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
namespace ProfileLocation.Domain.ORM.Interfaces
{
    public interface IUserContext
    {
        string Username { get; }
        string DisplayName { get; }
        int UserID { get; }
        string[] Roles { get; }
        string[] Scopes { get; }
        int ApplicationID { get; }
    }
}