// <copyright file="PagedList.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text;
using ProfileLocation.Domain.ORM.Interfaces;

namespace ProfileLocation.Domain.ORM.Implementations
{
    public class PagedList<TObject> : IPagedList<TObject> where TObject : class
    {
        public PagedList(IList<TObject> items, int resultTotal, int currentPage, int pageSize)
        {
            TotalCount = resultTotal;
            CurrentPage = currentPage;
            PageSize = pageSize;
            Items = items;
        }

        public IList<TObject> Items { get; }
        public int TotalCount { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }

        public int PageCount => (int) Math.Ceiling((double) TotalCount / PageSize);
    }
}
