// <copyright file="EntityObjectEventMessageModel.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text;
using ProfileLocation.Domain.ORM.Enums;

namespace ProfileLocation.Domain.ORM.Models.Communications
{
    public class EntityObjectEventMessageModel
    {
        public EntityObjectEventTypeEnum EventType { get; set; }
        public object Entity { get; set; }
    }
}
