// <auto-generated />
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProfileLocation.Domain.ORM.Models
{
    [Table("Group")]
    public partial class Group
    {
        public Group()
        {
            ProfileGroups = new HashSet<ProfileGroup>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        public bool IsDeleted { get; set; }

        [InverseProperty(nameof(ProfileGroup.Group))]
        public virtual ICollection<ProfileGroup> ProfileGroups { get; set; }
    }
}
