// <auto-generated />
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProfileLocation.Domain.ORM.Models
{
    [Table("Profile")]
    public partial class Profile
    {
        public Profile()
        {
            ProfileGroups = new HashSet<ProfileGroup>();
            Socials = new HashSet<Social>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(250)]
        public string Username { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        public string Bio { get; set; }
        [StringLength(250)]
        public string Nicknames { get; set; }
        [StringLength(250)]
        public string Email { get; set; }
        [StringLength(3)]
        public string Country { get; set; }
        [StringLength(250)]
        public string Mobile { get; set; }
        public int? LocationId { get; set; }
        [Column("PhotoURL")]
        [StringLength(250)]
        public string PhotoUrl { get; set; }
        public bool IsApproved { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActive { get; set; }
        public Guid Guid { get; set; }

        [ForeignKey(nameof(LocationId))]
        [InverseProperty("Profiles")]
        public virtual Location Location { get; set; }
        [InverseProperty(nameof(ProfileGroup.Profile))]
        public virtual ICollection<ProfileGroup> ProfileGroups { get; set; }
        [InverseProperty(nameof(Social.Profile))]
        public virtual ICollection<Social> Socials { get; set; }
    }
}
