// <auto-generated />
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProfileLocation.Domain.ORM.Models
{
    [Table("ProfileGroup")]
    public partial class ProfileGroup
    {
        [Key]
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public int GroupId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }

        [ForeignKey(nameof(GroupId))]
        [InverseProperty("ProfileGroups")]
        public virtual Group Group { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileGroups")]
        public virtual Profile Profile { get; set; }
    }
}
