// <auto-generated />
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProfileLocation.Domain.ORM.Models
{
    [Table("Social")]
    public partial class Social
    {
        [Key]
        public int Id { get; set; }
        public int SocialTypeId { get; set; }
        [Required]
        [StringLength(250)]
        public string Value { get; set; }
        [StringLength(250)]
        public string PhotoUrl { get; set; }
        public bool IsDeleted { get; set; }
        public int ProfileId { get; set; }

        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("Socials")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(SocialTypeId))]
        [InverseProperty("Socials")]
        public virtual SocialType SocialType { get; set; }
    }
}
