// <copyright file="ProfileGroupType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Linq;
using Microsoft.Extensions.DependencyInjection;
using GraphQL;
using GraphQL.DataLoader;
using GraphQL.Resolvers;
using GraphQL.Types;
using Microsoft.EntityFrameworkCore;
using ProfileLocation.Data.EF.Entities;
using ProfileLocation.Data.EF.Contexts;
using ProfileLocation.Domain.ORM.Interfaces;
using ProfileLocation.Domain.ORM.Models;

namespace ProfileLocation.WebAPI.Models.GraphQL
{
	public class ProfileGroupType : ObjectGraphType<ProfileGroup>
	{
		public ProfileGroupType(IDataLoaderContextAccessor accessor)
		{
            Name = "ProfileGroupQLType";
 
    		var fldId = Field(typeof(int).GetGraphTypeFromType(false), "Id");
			fldId.Resolver = new FuncFieldResolver<ProfileGroup,object>(ctx => ctx.Source.Id);
 
    		var fldProfileId = Field(typeof(int).GetGraphTypeFromType(false), "ProfileId");
			fldProfileId.Resolver = new FuncFieldResolver<ProfileGroup,object>(ctx => ctx.Source.ProfileId);
 
    		var fldGroupId = Field(typeof(int).GetGraphTypeFromType(false), "GroupId");
			fldGroupId.Resolver = new FuncFieldResolver<ProfileGroup,object>(ctx => ctx.Source.GroupId);
 
    		var fldIsActive = Field(typeof(bool).GetGraphTypeFromType(false), "IsActive");
			fldIsActive.Resolver = new FuncFieldResolver<ProfileGroup,object>(ctx => ctx.Source.IsActive);
 
    		var fldIsDeleted = Field(typeof(bool).GetGraphTypeFromType(false), "IsDeleted");
			fldIsDeleted.Resolver = new FuncFieldResolver<ProfileGroup,object>(ctx => ctx.Source.IsDeleted);

            var fldGroup = Field(typeof(GroupType), "Group");
			fldGroup.Resolver = new FuncFieldResolver<ProfileGroup,object>(ctx => 
            { 
                var poItemsLoader = accessor.Context.GetOrAddBatchLoader<int, ProfileLocation.Domain.ORM.Models.Group>("GetGroupByGroupId", async ids => 
                { 
                    var repo = ((QLUserContext) ctx.UserContext).ServiceProvider.GetService<IRepository<ProfileLocation.Domain.ORM.Models.Group>>(); 
                    var search = await repo.SearchAsync(s => ids.Contains(s.Id), int.MaxValue); 
                    return search.Items.ToDictionary(k => k.Id, v => v);
                }); 
 
                return poItemsLoader.LoadAsync(ctx.Source.GroupId); 
            });
    
            var fldProfile = Field(typeof(ProfileType), "Profile");
			fldProfile.Resolver = new FuncFieldResolver<ProfileGroup,object>(ctx => 
            { 
                var poItemsLoader = accessor.Context.GetOrAddBatchLoader<int, ProfileLocation.Domain.ORM.Models.Profile>("GetProfileByProfileId", async ids => 
                { 
                    var repo = ((QLUserContext) ctx.UserContext).ServiceProvider.GetService<IRepository<ProfileLocation.Domain.ORM.Models.Profile>>(); 
                    var search = await repo.SearchAsync(s => ids.Contains(s.Id), int.MaxValue); 
                    return search.Items.ToDictionary(k => k.Id, v => v);
                }); 
 
                return poItemsLoader.LoadAsync(ctx.Source.ProfileId); 
            });
    
        }

    }

}