// <copyright file="Program.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using ProfileLocation.Domain.ORM.Implementations;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using NLog.Web;

namespace ProfileLocation.WebAPI
{
    public class Program
    {
        public static int Main(string[] args)
        {
            var logger = NLog.Web.NLogBuilder.ConfigureNLog(DefaultLogger.DefaultConfiguration()).GetCurrentClassLogger();
            try
            {
                logger.Debug("Starting host...");
                CreateHostBuilder(args).Build().Run();
                return 0;
            }
            catch (Exception ex)
            {
                logger.Fatal(ex, "Host terminated unexpectedly.");
                return 1;
            }
            finally
            {
                NLog.LogManager.Shutdown();
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .ConfigureLogging(logging => { logging.ClearProviders(); })
                .UseNLog();
    }
}
