// <copyright file="GraphQLController.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraphQL;
using GraphQL.DataLoader;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using ProfileLocation.WebAPI.Models;
using ProfileLocation.WebAPI.Schema;
using ProfileLocation.WebAPI.Schema.Query;
using ProfileLocation.Domain.ORM.Interfaces;
using ProfileLocation.WebAPI.Models.GraphQL;

namespace ProfileLocation.WebAPI.Controllers
{
    [Authorize]
    public class GraphQLController : Controller
    {
        private readonly ProfileLocationSchema _schema;
        private readonly ILogManager _logManager;
        private readonly IConfiguration _configuration;

        public GraphQLController(ProfileLocationSchema schema, ILogManager logManager, IConfiguration configuration)
        {
            _schema = schema;
            _logManager = logManager;
            _configuration = configuration;
        }

        [HttpPost]
        public async Task<IActionResult> Index([FromBody] GraphQLQuery query)
        {
            var inputs = query.Variables.ToInputs();
            var resolver = HttpContext.RequestServices;

            var result = await new DocumentExecuter().ExecuteAsync(_ =>
            {
                _.Schema = _schema;
                _.Listeners.Add(resolver.GetService(typeof(DataLoaderDocumentListener)).As<DataLoaderDocumentListener>());
                _.Query = query.Query;
                _.OperationName = query.OperationName;
                _.Inputs = inputs;
                _.UserContext = new QLUserContext(HttpContext);
            }).ConfigureAwait(false);

            if(result.Errors?.Count > 0)
            {
                _logManager.Fatal("Error in QL request: " + query.Query, new AggregateException(result.Errors));
                return StatusCode(500, new { Count = result.Errors.Count, Errors = result.Errors.Select(GetErrorModel).ToArray()});
            }

            return Ok(result);
        }

        [HttpGet]
        [AllowAnonymous]
        public Task<IActionResult> Index()
        {
            var clientId = _configuration.GetSection("Security:ApplicationName").Get<string>();
            var scopes = _configuration.GetSection("Security:Scopes").Get<List<string>>();
            var idServer = _configuration.GetSection("Security:IDServer").Get<string>();
            
            if (clientId == null || scopes == null || !scopes.Any() || idServer == null) throw new ArgumentException("Invalid config in security section in appsettings");

            var returnUrl = $"{Request.Scheme}://{Request.Host}{Request.PathBase}/GraphQL/UIAuth";

            return Task.FromResult((IActionResult) Redirect($"{idServer}connect/authorize?client_id={clientId}&redirect_uri={returnUrl}&scope={string.Join(" ", scopes)}&nonce={DateTime.Now.Ticks}&response_type=token&response_mode=form_post"));
        }

        [HttpPost]
        [AllowAnonymous]
        public Task<IActionResult> UIAuth([FromForm] string access_token, string token_type, int expires_in, string scope)
        {
            return Task.FromResult((IActionResult) View("QLPlayground", access_token));
        }

        private ErrorModel GetErrorModel(Exception e)
        {
            if (e?.InnerException == null)
            {
                return new ErrorModel()
                {
                    ErrorCode = e.HResult.ToString(),
                    Message = e.Message,
                    ExceptionType = e.GetType().Name,
#if DEBUG
                    Debug = e.ToString()
#endif
                };
            }
            else
            {
                return GetErrorModel(e.InnerException);
            }
        }
    }
}
