// <copyright file="UserContextModel.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using ProfileLocation.Domain.ORM.Interfaces;

namespace ProfileLocation.Domain.ORM.Models
{
    public class UserContextModel : IUserContext
    {
        public string Username { get; set; }
        public string DisplayName { get; set; }
        public int UserID { get; set; }
        public string[] Roles { get; set; }
        public string[] Scopes { get; set; }
        public int ApplicationID { get; set; }
    }
}
