// <copyright file="LocationRepository.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using Microsoft.EntityFrameworkCore; 
using ProfileLocation.Data.EF.Contexts; 
using ProfileLocation.Domain.ORM.Models; 
using ProfileLocation.Domain.ORM.Interfaces; 
 
namespace ProfileLocation.Data.EF.Repositories 
{ 
    public class LocationRepository : BaseRepository<Location> 
    { 
        public LocationRepository(ProfileLocationContext context, ILogManager logManager = null) : base(context, x => x.Id , logManager) 
        { 
      
        } 
 
        public override DbSet<Location> EntityDbSet => ProfileLocationContext.Locations; 
    } 
}
