// <copyright file="ProfileLocationSchema.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Linq;
using ProfileLocation.WebAPI.Schema.Mutation;
using ProfileLocation.WebAPI.Schema.Query;
using ProfileLocation.WebAPI.Schema.Subscription;

namespace ProfileLocation.WebAPI.Schema
{
    public class ProfileLocationSchema : GraphQL.Types.Schema
    {
        public ProfileLocationSchema(ProfileLocationQuery query, ProfileLocationMutations mutation, ProfileLocationSubscriptions subscriptions, IServiceProvider serviceProvider)
        {
            Query = query;
            Subscription = subscriptions;
            Services = serviceProvider;
            
            if (mutation.Fields.Any())
            {
                Mutation = mutation;
            }
        }
    }
}
