// <copyright file="LocationEnumType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using GraphQL.Types; 

namespace ProfileLocation.WebAPI.Models.GraphQL.EntityFieldEnums
{
	public class LocationEnumType : EnumerationGraphType
	{
		public LocationEnumType()
		{
			Name = "Location";

            AddValue("id", "", "Id"); 
            AddValue("address", "", "Address"); 
            AddValue("viewPort", "", "ViewPort"); 
            AddValue("location1", "", "Location1"); 
            AddValue("placeId", "", "PlaceId"); 
            AddValue("profileId", "", "ProfileId"); 
		}
	}
}