// <copyright file="ProfileEnumType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using GraphQL.Types; 

namespace ProfileLocation.WebAPI.Models.GraphQL.EntityFieldEnums
{
	public class ProfileEnumType : EnumerationGraphType
	{
		public ProfileEnumType()
		{
			Name = "Profile";

            AddValue("id", "", "Id"); 
            AddValue("username", "", "Username"); 
            AddValue("name", "", "Name"); 
            AddValue("bio", "", "Bio"); 
            AddValue("nicknames", "", "Nicknames"); 
            AddValue("email", "", "Email"); 
            AddValue("country", "", "Country"); 
            AddValue("mobile", "", "Mobile"); 
            AddValue("locationId", "", "LocationId"); 
            AddValue("photoUrl", "", "PhotoUrl"); 
            AddValue("isApproved", "", "IsApproved"); 
            AddValue("isAdmin", "", "IsAdmin"); 
            AddValue("isActive", "", "IsActive"); 
            AddValue("guid", "", "Guid"); 
		}
	}
}