// <copyright file="SocialEnumType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using GraphQL.Types; 

namespace ProfileLocation.WebAPI.Models.GraphQL.EntityFieldEnums
{
	public class SocialEnumType : EnumerationGraphType
	{
		public SocialEnumType()
		{
			Name = "Social";

            AddValue("id", "", "Id"); 
            AddValue("socialTypeId", "", "SocialTypeId"); 
            AddValue("value", "", "Value"); 
            AddValue("photoUrl", "", "PhotoUrl"); 
            AddValue("isDeleted", "", "IsDeleted"); 
            AddValue("profileId", "", "ProfileId"); 
		}
	}
}