// <copyright file="SocialTypeEnumType.cs" company="">
// Copyright (c) . All rights reserved.
// </copyright>
// <auto-generated />
using GraphQL.Types; 

namespace ProfileLocation.WebAPI.Models.GraphQL.EntityFieldEnums
{
	public class SocialTypeEnumType : EnumerationGraphType
	{
		public SocialTypeEnumType()
		{
			Name = "SocialType";

            AddValue("id", "", "Id"); 
            AddValue("name", "", "Name"); 
            AddValue("iconUrl", "", "IconUrl"); 
            AddValue("isDeleted", "", "IsDeleted"); 
		}
	}
}