// <copyright file="QLIgnoreAttribute.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text;

namespace ProfileLocation.Domain.ORM.Attributes
{
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Class)]
    public class QLIgnoreAttribute : Attribute
    {
    }
}
