// <copyright file="QLQueryAttribute.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text;

namespace ProfileLocation.Domain.ORM.Attributes
{
    [AttributeUsage(AttributeTargets.Method)]
    public class QLQueryAttribute : Attribute
    {
    }
}
