// <copyright file="StringSearchModel.cs" company="Victor Saly">
// Copyright (c) Victor Saly. All rights reserved.
// </copyright>
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProfileLocation.WebAPI.Models
{
    public class StringSearchModel
    {
        public new string Equals { get; set; }
        public string NotEqual { get; set; }
        public string StartsWith { get; set; }
        public string Contains { get; set; }
        public string EndsWith { get; set; }
    }
}
